name: Python CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install ODBC Driver
      run: |
        sudo apt-get update
        sudo apt-get install -y unixodbc unixodbc-dev
        sudo apt-get install -y tdsodbc

    - name: Install Python packages
      run: |
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        pytest

    - name: Install SQL Server ODBC Driver
      run: |
        sudo apt-get update
        sudo ACCEPT_EULA=Y apt-get install -y msodbcsql17